const types = {
    ADD_SONG: "ADD_SONG",
    REMOVE_SONG: "REMOVE_SONG",
    EXPORT_PLAYLISTS: "EXPORT_PLAYLISTS",
    IMPORT_TRACKS: "IMPORT_TRACKS",
    CLEAR_TRACKS: "CLEAR_TRACKS",
    CLEAR: "CLEAR",
    TOGGLE_HELP: "TOGGLE_HELP",
    LOGIN: "LOGIN"
  };
  
  export default types;